// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StreetEmpire.Api.Data;

#nullable disable

namespace StreetEmpire.Api.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260818005004_ShrineAndTitles")]
    partial class ShrineAndTitles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StreetEmpire.Api.Models.AdminAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ActorAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorUsername")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("TargetName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("TargetPlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("TargetPlayerId");

                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.CombatLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttackerHoesLost")
                        .HasColumnType("integer");

                    b.Property<Guid>("AttackerId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttackerPimpsLost")
                        .HasColumnType("integer");

                    b.Property<int>("AttackerPower")
                        .HasColumnType("integer");

                    b.Property<int>("AttackerThugsLost")
                        .HasColumnType("integer");

                    b.Property<int>("AttackerWeaponsLost")
                        .HasColumnType("integer");

                    b.Property<long>("CashStolen")
                        .HasColumnType("bigint");

                    b.Property<int>("CokeStolen")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefenderHoesLost")
                        .HasColumnType("integer");

                    b.Property<Guid>("DefenderId")
                        .HasColumnType("uuid");

                    b.Property<int>("DefenderPimpsLost")
                        .HasColumnType("integer");

                    b.Property<int>("DefenderPower")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DefenderProtectionUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefenderThugsLost")
                        .HasColumnType("integer");

                    b.Property<int>("DefenderWeaponsLost")
                        .HasColumnType("integer");

                    b.Property<int>("HoesTaken")
                        .HasColumnType("integer");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResolvesAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RidesTaken")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<long?>("TerritoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("TurnsSpent")
                        .HasColumnType("integer");

                    b.Property<int>("WeedStolen")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttackerId", "CreatedAtUtc");

                    b.HasIndex("DefenderId", "CreatedAtUtc");

                    b.HasIndex("Outcome", "ResolvesAtUtc");

                    b.ToTable("CombatLogs");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.CombatMission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ArrivesAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AssignedPimps")
                        .HasColumnType("integer");

                    b.Property<int>("AssignedThugs")
                        .HasColumnType("integer");

                    b.Property<int>("AssignedWeapons")
                        .HasColumnType("integer");

                    b.Property<int>("AttackerHoesLost")
                        .HasColumnType("integer");

                    b.Property<Guid>("AttackerId")
                        .HasColumnType("uuid");

                    b.Property<double>("AttackerMorale")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("AttackerPimpsLost")
                        .HasColumnType("integer");

                    b.Property<int>("AttackerPower")
                        .HasColumnType("integer");

                    b.Property<int>("AttackerThugsLost")
                        .HasColumnType("integer");

                    b.Property<int>("AttackerWeaponsLost")
                        .HasColumnType("integer");

                    b.Property<int>("CarriedPistols")
                        .HasColumnType("integer");

                    b.Property<int>("CarriedRifles")
                        .HasColumnType("integer");

                    b.Property<int>("CarriedShotguns")
                        .HasColumnType("integer");

                    b.Property<int>("CarriedSmgs")
                        .HasColumnType("integer");

                    b.Property<long>("CashStolen")
                        .HasColumnType("bigint");

                    b.Property<int>("CokeStolen")
                        .HasColumnType("integer");

                    b.Property<int>("CommanderBonusPercent")
                        .HasColumnType("integer");

                    b.Property<string>("CommanderName")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<long?>("CommanderPimpId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<int>("DefenderHoesLost")
                        .HasColumnType("integer");

                    b.Property<Guid>("DefenderId")
                        .HasColumnType("uuid");

                    b.Property<double>("DefenderMorale")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("DefenderPimpsLost")
                        .HasColumnType("integer");

                    b.Property<int>("DefenderPower")
                        .HasColumnType("integer");

                    b.Property<int>("DefenderProtectionMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DefenderProtectionUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefenderRecentHits")
                        .HasColumnType("integer");

                    b.Property<int>("DefenderThugsLost")
                        .HasColumnType("integer");

                    b.Property<int>("DefenderWeaponsLost")
                        .HasColumnType("integer");

                    b.Property<int>("LootMultiplierPercent")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRounds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextRoundAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RemainingAttackers")
                        .HasColumnType("integer");

                    b.Property<int>("RemainingWeapons")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReturnsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<long?>("TerritoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("TurnsSpent")
                        .HasColumnType("integer");

                    b.Property<int>("WeedStolen")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommanderPimpId");

                    b.HasIndex("TerritoryId");

                    b.HasIndex("AttackerId", "Status");

                    b.HasIndex("DefenderId", "Status");

                    b.HasIndex("Status", "ArrivesAtUtc", "NextRoundAtUtc", "ReturnsAtUtc");

                    b.ToTable("CombatMissions");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.CombatMissionEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AttackRoll")
                        .HasPrecision(8, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("AttackerMorale")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("AttackerThugsLost")
                        .HasColumnType("integer");

                    b.Property<int>("AttackerWeaponsLost")
                        .HasColumnType("integer");

                    b.Property<long>("CombatMissionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DefenderMorale")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("DefenderThugsLost")
                        .HasColumnType("integer");

                    b.Property<int>("DefenderWeaponsLost")
                        .HasColumnType("integer");

                    b.Property<double>("DefenseRoll")
                        .HasPrecision(8, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.HasKey("Id");

                    b.HasIndex("CombatMissionId", "CreatedAtUtc");

                    b.ToTable("CombatMissionEvents");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Buyer")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FilledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FilledById")
                        .HasColumnType("uuid");

                    b.Property<string>("Good")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("ListPricePerUnit")
                        .HasColumnType("bigint");

                    b.Property<int?>("MinimumPurityPercent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PricePerUnit")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FilledById");

                    b.HasIndex("City", "FilledAtUtc", "ExpiresAtUtc");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.GameActionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("BankDelta")
                        .HasColumnType("bigint");

                    b.Property<int>("BeerDelta")
                        .HasColumnType("integer");

                    b.Property<long>("CashDelta")
                        .HasColumnType("bigint");

                    b.Property<int>("CokeDelta")
                        .HasColumnType("integer");

                    b.Property<int>("CondomsDelta")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("HoeMoraleBefore")
                        .HasColumnType("double precision");

                    b.Property<int>("HoesDelta")
                        .HasColumnType("integer");

                    b.Property<int>("PimpsDelta")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<double?>("ThugMoraleBefore")
                        .HasColumnType("double precision");

                    b.Property<int>("ThugsDelta")
                        .HasColumnType("integer");

                    b.Property<int>("TurnsSpent")
                        .HasColumnType("integer");

                    b.Property<int>("WeaponsDelta")
                        .HasColumnType("integer");

                    b.Property<int>("WeedDelta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "CreatedAtUtc");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.GameSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Announcement")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<bool>("BotAutomationEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("BotRoundsPerTick")
                        .HasColumnType("integer");

                    b.Property<int?>("BotTickSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("ConfigOverridesJson")
                        .HasColumnType("text");

                    b.Property<string>("MaintenanceMessage")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<bool>("MaintenanceMode")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("GameSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BotAutomationEnabled = false,
                            MaintenanceMode = false,
                            UpdatedAtUtc = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.Hideout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CokeLabLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntelligenceLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LabsCollectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LookoutLevel")
                        .HasColumnType("integer");

                    b.Property<int>("MixLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SafeLevel")
                        .HasColumnType("integer");

                    b.Property<int>("StillLevel")
                        .HasColumnType("integer");

                    b.Property<int>("StorageLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpgradeCompletesAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpgradingToTier")
                        .HasColumnType("integer");

                    b.Property<int>("WeedLabLevel")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Hideouts");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.MarketListing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("OriginalQuantity")
                        .HasColumnType("integer");

                    b.Property<long>("PricePerUnit")
                        .HasColumnType("bigint");

                    b.Property<double>("Purity")
                        .HasColumnType("double precision");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.HasIndex("Item", "PricePerUnit");

                    b.ToTable("MarketListings");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.MuleRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ArrivesAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AssignedHoes")
                        .HasColumnType("integer");

                    b.Property<int>("BustChancePercent")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<long>("CashReturned")
                        .HasColumnType("bigint");

                    b.Property<long>("CashSent")
                        .HasColumnType("bigint");

                    b.Property<int>("DefectChancePercent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DepartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationCity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Good")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double>("HeatAdded")
                        .HasColumnType("double precision");

                    b.Property<int>("HoesLost")
                        .HasColumnType("integer");

                    b.Property<string>("OriginCity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long?>("PimpId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PimpLost")
                        .HasColumnType("boolean");

                    b.Property<double>("PimpLoyaltyAtLaunch")
                        .HasColumnType("double precision");

                    b.Property<string>("PimpName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReturnsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeizedUnits")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SettledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TravelCost")
                        .HasColumnType("bigint");

                    b.Property<int>("TurnsSpent")
                        .HasColumnType("integer");

                    b.Property<long>("UnitPricePaid")
                        .HasColumnType("bigint");

                    b.Property<int>("UnitsBought")
                        .HasColumnType("integer");

                    b.Property<long>("UpkeepCost")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PimpId");

                    b.HasIndex("ReturnsAtUtc");

                    b.HasIndex("PlayerId", "SettledAtUtc");

                    b.ToTable("MuleRuns");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.Pimp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BonusPercent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LostAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LostReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("Loyalty")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("MissionsLed")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Victories")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "LostAtUtc");

                    b.ToTable("Pimps");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<long>("BankCash")
                        .HasColumnType("bigint");

                    b.Property<int>("Beer")
                        .HasColumnType("integer");

                    b.Property<long>("Cash")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CatchUpSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Coke")
                        .HasColumnType("integer");

                    b.Property<double>("CokePurity")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CombatAlertsSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CombatProtectionUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Condoms")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Cut")
                        .HasColumnType("integer");

                    b.Property<double>("Heat")
                        .HasColumnType("double precision");

                    b.Property<int>("HoeCutPercent")
                        .HasColumnType("integer");

                    b.Property<double>("HoeHappiness")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("Hoes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastAttackAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastAttackedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastHeatRollUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastPrayedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastTurnUpdateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Medicine")
                        .HasColumnType("integer");

                    b.Property<int>("Moonshine")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Pimps")
                        .HasColumnType("integer");

                    b.Property<int>("Pistols")
                        .HasColumnType("integer");

                    b.Property<int>("Rides")
                        .HasColumnType("integer");

                    b.Property<int>("Rifles")
                        .HasColumnType("integer");

                    b.Property<int>("Shotguns")
                        .HasColumnType("integer");

                    b.Property<int>("Smgs")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StrikeProtectionUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ThugHappiness")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("Thugs")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TravelArrivesAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Turns")
                        .HasColumnType("integer");

                    b.Property<int>("Weed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.PlayerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BotNextSessionAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BotSessionActionsLeft")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("BotSessionEndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnforcementReason")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBotPaused")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SessionsValidAfterUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SuspendedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.StandingSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("NetWorth")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TakenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TakenAtUtc");

                    b.HasIndex("PlayerId", "TakenAtUtc");

                    b.ToTable("StandingSnapshots");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.Territory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("GarrisonPimpId")
                        .HasColumnType("bigint");

                    b.Property<int>("GarrisonThugs")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HeldSinceUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HolderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<DateTime?>("ProtectedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("GarrisonPimpId");

                    b.HasIndex("HolderId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Territories");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.CombatLog", b =>
                {
                    b.HasOne("StreetEmpire.Api.Models.Player", "Attacker")
                        .WithMany("AttacksMade")
                        .HasForeignKey("AttackerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StreetEmpire.Api.Models.Player", "Defender")
                        .WithMany("Defenses")
                        .HasForeignKey("DefenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attacker");

                    b.Navigation("Defender");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.CombatMission", b =>
                {
                    b.HasOne("StreetEmpire.Api.Models.Player", "Attacker")
                        .WithMany("MissionsStarted")
                        .HasForeignKey("AttackerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StreetEmpire.Api.Models.Pimp", "CommanderPimp")
                        .WithMany()
                        .HasForeignKey("CommanderPimpId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StreetEmpire.Api.Models.Player", "Defender")
                        .WithMany("MissionsDefended")
                        .HasForeignKey("DefenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StreetEmpire.Api.Models.Territory", "Territory")
                        .WithMany()
                        .HasForeignKey("TerritoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Attacker");

                    b.Navigation("CommanderPimp");

                    b.Navigation("Defender");

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.CombatMissionEvent", b =>
                {
                    b.HasOne("StreetEmpire.Api.Models.CombatMission", "CombatMission")
                        .WithMany("Events")
                        .HasForeignKey("CombatMissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CombatMission");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.Contract", b =>
                {
                    b.HasOne("StreetEmpire.Api.Models.Player", "FilledBy")
                        .WithMany()
                        .HasForeignKey("FilledById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FilledBy");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.GameActionLog", b =>
                {
                    b.HasOne("StreetEmpire.Api.Models.Player", "Player")
                        .WithMany("ActionLogs")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.Hideout", b =>
                {
                    b.HasOne("StreetEmpire.Api.Models.Player", "Player")
                        .WithOne("Hideout")
                        .HasForeignKey("StreetEmpire.Api.Models.Hideout", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.MarketListing", b =>
                {
                    b.HasOne("StreetEmpire.Api.Models.Player", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.MuleRun", b =>
                {
                    b.HasOne("StreetEmpire.Api.Models.Pimp", "Pimp")
                        .WithMany()
                        .HasForeignKey("PimpId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StreetEmpire.Api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pimp");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.Pimp", b =>
                {
                    b.HasOne("StreetEmpire.Api.Models.Player", "Player")
                        .WithMany("Crew")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.Player", b =>
                {
                    b.HasOne("StreetEmpire.Api.Models.PlayerAccount", "Account")
                        .WithOne("Player")
                        .HasForeignKey("StreetEmpire.Api.Models.Player", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.StandingSnapshot", b =>
                {
                    b.HasOne("StreetEmpire.Api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.Territory", b =>
                {
                    b.HasOne("StreetEmpire.Api.Models.Pimp", "GarrisonPimp")
                        .WithMany()
                        .HasForeignKey("GarrisonPimpId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StreetEmpire.Api.Models.Player", "Holder")
                        .WithMany()
                        .HasForeignKey("HolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GarrisonPimp");

                    b.Navigation("Holder");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.CombatMission", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.Player", b =>
                {
                    b.Navigation("ActionLogs");

                    b.Navigation("AttacksMade");

                    b.Navigation("Crew");

                    b.Navigation("Defenses");

                    b.Navigation("Hideout");

                    b.Navigation("MissionsDefended");

                    b.Navigation("MissionsStarted");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.PlayerAccount", b =>
                {
                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
