// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StreetEmpire.Api.Data;

#nullable disable

namespace StreetEmpire.Api.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260810031500_AddBotAccounts")]
    partial class AddBotAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StreetEmpire.Api.Models.GameActionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("BankDelta")
                        .HasColumnType("bigint");

                    b.Property<int>("BeerDelta")
                        .HasColumnType("integer");

                    b.Property<long>("CashDelta")
                        .HasColumnType("bigint");

                    b.Property<int>("CokeDelta")
                        .HasColumnType("integer");

                    b.Property<int>("CondomsDelta")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HoesDelta")
                        .HasColumnType("integer");

                    b.Property<int>("PimpsDelta")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<int>("ThugsDelta")
                        .HasColumnType("integer");

                    b.Property<int>("TurnsSpent")
                        .HasColumnType("integer");

                    b.Property<int>("WeaponsDelta")
                        .HasColumnType("integer");

                    b.Property<int>("WeedDelta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "CreatedAtUtc");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<long>("BankCash")
                        .HasColumnType("bigint");

                    b.Property<int>("Beer")
                        .HasColumnType("integer");

                    b.Property<long>("Cash")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Coke")
                        .HasColumnType("integer");

                    b.Property<int>("Condoms")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HoeCutPercent")
                        .HasColumnType("integer");

                    b.Property<double>("HoeHappiness")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("Hoes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastTurnUpdateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Pimps")
                        .HasColumnType("integer");

                    b.Property<double>("ThugHappiness")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("Thugs")
                        .HasColumnType("integer");

                    b.Property<int>("Turns")
                        .HasColumnType("integer");

                    b.Property<int>("Weapons")
                        .HasColumnType("integer");

                    b.Property<int>("Weed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.PlayerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.GameActionLog", b =>
                {
                    b.HasOne("StreetEmpire.Api.Models.Player", "Player")
                        .WithMany("ActionLogs")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.Player", b =>
                {
                    b.HasOne("StreetEmpire.Api.Models.PlayerAccount", "Account")
                        .WithOne("Player")
                        .HasForeignKey("StreetEmpire.Api.Models.Player", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.Player", b =>
                {
                    b.Navigation("ActionLogs");
                });

            modelBuilder.Entity("StreetEmpire.Api.Models.PlayerAccount", b =>
                {
                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
